# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3513ed2bc4c7756c87db0c7ef38710f803cba4c4591cff760defcfb0a20bc1d9df678aa53313d98846e3aa952718c5bf8d95b29133c4620fc1afec191c90d43e

test:
  secret_key_base: 631da0140d1ccaa53a044fcf639ee398eb66b1daf2ab0f758a888d4551be1ba31c6c81e698d66af27700d02c2aca05506c7921d5d413523a867017f0e35264d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
